### ISSUE TITLE
关于输入x维度不匹配的问题

### ISSUE THREAD

**Issue by SileiZhao** [wizardbo/Slowfast-CBAM#1]
在video_model_builder.py中，SlowFast类的forward函数，输入的x是一个list，x[0]表示慢通道，维度为[1, 3, 8, 224, 224]，x[1]表示快通道，维度为[1, 3, 32, 224, 224]，在经过cbam层时，由于维度不同，会报错，‘list’ object has no attribute ‘size’，我尝试将x转换为Tenosr，但是我不太清楚如何拼接这两个维度的数据，或者慢通道和快通道分别进行cbam计算吗？
<img width="1238" alt="iShot_2024-04-24_09 33 21" src="https://github.com/wizardbo/Slowfast-CBAM/assets/72799040/fd15d94f-ad39-46b0-9b70-2c4cb644d0a9">
感谢您的解答！

**Comment by wizardbo** [comment]
Thanks for your focus on this project, we suggest you don't convert `x` to `Tensor`, but consider using `torch.cat` to merge all tensor output by CBAM modules.

**Comment by wizardbo** [comment]
If your have no further question, we will close this issue in 2 day.
